### ISSUE TITLE
Updated the main navigation

### ISSUE THREAD

**Issue by dandange8005** [dandange8005/Ultra-Essentials#33]
I have updated the project main navigation:
![main navigation](https://github.com/dandange8005/Ultra-Essentials/assets/5180820/23166172-61a4-4614-992e-6beed3649fd8)

with the following css code

```css
/* Expand the navigation to take up full width when screensize larger than 980px */

@media (min-width: 980px) {
  .navbar .container {
    width: 100%;
    display: flex;
    justify-content: center;
  }
}

```
