### ISSUE TITLE
New Banner background

### ISSUE THREAD

**Issue by dandange8005** [dandange8005/Ultra-Essentials#50]
New banner background has now been created:

```css

// Add the following custom properties to the root 

:root {
  --clr-jumbotron-bg: hsla(241,41%,18%,1);
  --clr-jumbotron-bg-gradient: 
  radial-gradient(at 100% 100%, hsla(289,93%,28%,1) 0px, transparent 50%),
radial-gradient(at 1% 97%, hsla(220,64%,11%,1) 0px, transparent 50%),
radial-gradient(at 0% 0%, hsla(202,87%,44%,1) 0px, transparent 50%);
}

```
